[frontends]
  [frontends.service]
  backend = "service"
  entrypoints = ["web"]
    [frontends.service.routes.test_1]
    rule = "Path:/"

[backends]
  [backends.service]
    [backends.service.servers.server1]
    url = "http://172.19.0.2:8866"